function sun = importfile_sun(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   SUN = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   SUN = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   sun = importfile1('sun.csv', 2, 105121);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/07/31 21:58:17

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: datetimes (%{MM/dd/yyyy HH:mm}D)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{MM/dd/yy HH:mm}D%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
sun = table(dataArray{1:end-1}, 'VariableNames', {'LocalTime','PowerMW'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% sun.LocalTime=datenum(sun.LocalTime);

