function demandsimulation = import_demand_simulation(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   DEMANDSIMULATION = demand_simulation(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   DEMANDSIMULATION = demand_simulation(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   demandsimulation = importfile1('demand_simulation.csv', 2, 49);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/10/09 22:24:20

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: datetimes (%{MM/dd/yyyy HH:mm}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: text (%s)
%	column8: text (%s)
%   column9: text (%s)
%	column10: text (%s)
%   column11: text (%s)
%	column12: text (%s)
%   column13: text (%s)
%	column14: double (%f)
%   column15: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%{MM/dd/yyyy HH:mm}D%f%f%f%f%f%s%s%s%s%s%s%s%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
demandsimulation = table(dataArray{1:end-1}, 'VariableNames', {'Time','BaselineCpucoreshoursSimulator1','BaselineCpucoreshoursSimulator2','BaselineCpucoreshoursSimulator3','BaselineCpucoreshoursSimulator4','EUserverskWh','VarName7','VarName8','VarName9','VarName10','VarName11','VarName12','VarName13','VarName14','MtCO2e'});

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% demandsimulation.Time=datenum(demandsimulation.Time);

